# Generated by Django 4.1 on 2022-08-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_description_alter_product_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
